name: Generate data.json on GitHub Pages deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Make a copy of data.json
      run: cp data/data.json data/data.json.old || true  # Ensure copy even if data.json.old doesn't exist

    - name: Run Python script
      run: python3 data/data.py

    - name: Check if data.json changed
      id: check_changes
      run: |
        if [ -f "data/data.json.old" ]; then
          if diff -q data/data.json data/data.json.old; then
            echo "No changes to commit."
          else
            echo "Changes detected."
          fi
        else
          echo "No previous data.json file found."
          echo "Changes detected."  # Assume changes if no previous data.json file
        fi

    - name: Commit data.json
      if: steps.check_changes.outcome == 'success'
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add data/data.json
        git commit -m "Update data.json [skip ci]"
        git push
