name: Generate data.json

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run Python script
      run: python3 data/data.py

    - name: Check if data.json changed
      id: check_changes
      run: |
        if git diff --exit-code --quiet; then
          echo "No changes to commit."
          exit 0
        else
          echo "Changes detected."
          exit 1
        fi

    - name: Commit data.json
      if: steps.check_changes.outcome == 'failure'
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add data/data.json
        git commit -m "Update data.json [skip ci]"
        git push
