name: Generate data.json on GitHub Pages deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Make a copy of data.json
      run: |
        cp data/data.json data.old.json

    - name: Run Python script
      run: python3 data/data.py

    - name: Check if data.json changed
      id: check_changes
      run: |
        cat data.json
        cat data.old.json
        if diff -q data.json data.old.json; then
          echo "changed=false" >> $GITHUB_ENV
          echo "No changes to commit."
        else
          echo "changed=true" >> $GITHUB_ENV
          echo "Changes detected."
        fi

    - name: Remove old data.json
      run: rm data.old.json

    - name: Move data.json to the correct location
      if: env.changed == 'true'
      run: mv data.json data/data.json

    - name: Commit data.json
      if: env.changed == 'true'
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add data/data.json
        git commit -m "Update data.json [skip ci]"
        git push
